name: Scott Lee Johnson - Sculptor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88748
title: Works in Terra-cotta and Bronze
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9bd0f8'
    - '#699fdd'
    - '#3e786b'
    - '#3f5f01'
  brandStrength: 0.6875
  lightness: 0.5688034915365279
  saturation: 0.8399632310029119
  rhythmicContrast: 0.75
purpose: []
