name: Scott Lee Johnson - Sculptor
favicon: null
layout_spectrum: 0.631112038390711
typography_spectrum: 0.3904317149426788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.44188238494098186
  lightness: 0.5688034915365279
  saturation: 0.8399632310029119
  rhythmicContrast: 0.5752056778874248
purpose: []
